version: "3"

services:
  base: &base
    image: chatwoot/chatwoot:${SOFTWARE_VERSION_TAG}
    restart: always
    env_file: .env ## Change this file for customized env variables

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - 172.17.0.1:3000:3000
    restart: always
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    restart: always
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

  postgres:
    image: postgres:12
    restart: always
    ports:
      - "172.17.0.1:5432:5432"
    volumes:
      - /opt/app/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=${SOFTWARE_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - /opt/app/data/redis:/data
    ports:
      - "172.17.0.1:6379:6379"
